### ISSUE TITLE
能否更新一下，在新版的taichi下已经不能运行

### ISSUE THREAD

**Issue by zhaozhh** [theAfish/BlackHoleRayMarching#1]
您好！

如题所示，我的系统是：

[Taichi] version 1.7.2, llvm 15.0.1, commit 0131dce9, win, python 3.11.4

谢谢！！

**Comment by theAfish** [comment]
> 您好！
> 
> 如题所示，我的系统是：
> 
> [Taichi] version 1.7.2, llvm 15.0.1, commit 0131dce9, win, python 3.11.4
> 
> 谢谢！！

感谢关注本项目！由于目前没有在做相关的代码，因此只能简单修改一下bug了。

初步分析发现并非本库中代码的问题，而是其依赖库taichi_glsl已经停止更新无法适配最新版本taichi。不过初步尝试有一个简单的步骤让代码跑起来：

1. 手动修改taichi_glsl中的代码：将“你的python地址\Lib\site-packages\taichi_glsl\hack.py”中第11行
```_old_element_wise_binary = ti.Matrix._element_wise_binary```注释掉。
2. 代码中高斯模糊功能在新版本taichi中出现问题，暂时去掉就可以运行。使用如下文件中内容代替原先main.py即可。
[main.txt](https://github.com/user-attachments/files/17618589/main.txt)

**Comment by zhaozhh** [comment]
谢谢您的更新代码

就是不知道一般要运行多久？运行信息如下

[Taichi] version 1.7.2, llvm 15.0.1, commit 0131dce9, win, python 3.11.4
[TaiGLSL] version 0.0.12
[Taichi] Starting on arch=cuda

但是看了一下任务管理器，如下图，似乎英伟达的GPU并没有启动，不知为何？
![1730729922712](https://github.com/user-attachments/assets/ae92ecdd-c46e-470a-8146-e0932c84eaec)


程序报错了，信息如下

[E 11/04/24 22:36:38.450 16444] [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *,void *,unsigned __int64>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling memcpy_host_to_device (cuMemcpyHtoD_v2)


Traceback (most recent call last):
  File "d:\yun\WorkSpace\RelativityObjects\BlackHoleRayMarching-master\BlackHoleRayMarching-master\main.py", line 69, in <module>
    gui.set_image(np.sqrt(bloom_img.to_numpy() / cnt))
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\util.py", line 351, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\matrix.py", line 1271, in to_numpy
    matrix_to_ext_arr(self, arr, as_vector)
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1113, in wrapped
    return primal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\matrix.py", line 1271, in to_numpy
    matrix_to_ext_arr(self, arr, as_vector)
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1113, in wrapped
    return primal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\matrix.py", line 1271, in to_numpy
    matrix_to_ext_arr(self, arr, as_vector)
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1113, in wrapped
    return primal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1113, in wrapped
    return primal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 1045, in __call__
    return self.launch_kernel(kernel_cpp, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.launch_kernel(kernel_cpp, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 976, in launch_kernel
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 976, in launch_kernel
    raise e from None
  File "C:\Users\zhaozhh\AppData\Roaming\Python\Python311\site-packages\taichi\lang\kernel_impl.py", line 971, in launch_kernel
    prog.launch_kernel(compiled_kernel_data, launch_ctx)
RuntimeError: [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *,void *,unsigned __int64>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling memcpy_host_to_device (cuMemcpyHtoD_v2)
[E 11/04/24 22:36:38.940 16444] [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void *>::operator ()@92] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)

**Comment by theAfish** [comment]
我这边采用相同的python版本以及设置似乎没有问题：

![image](https://github.com/user-attachments/assets/00617e94-bedf-423b-a790-4ed498a66097)

程序运行基本不需要等候。可以先用cpu试一下是否可以正常运行，将main.py中第五行的ti.init(arch=ti.cuda) 改为 ti.init(arch=ti.cpu)

**Comment by zhaozhh** [comment]
感谢您的回复和测试，

GPU 选项运行和您的截图一致，上面的出错信息可能是因为我调节窗口的大小导致。


我们有一个新的问题，如何保存图片和动画，例如这三个文件

![图片](https://github.com/user-attachments/assets/25f2b7be-b827-440b-8cbf-995573d2f4c0)


![图片](https://github.com/user-attachments/assets/50ae7d91-8979-4a39-8168-e0ce863c03bb)



---------------------------------------------------------------------------------------------------------
还有一个问题：

但是当用cpu计算的时候，窗口中没有图片。
ti.init(arch=ti.cpu)
[Taichi] version 1.7.2, llvm 15.0.1, commit 0131dce9, win, python 3.11.4
[TaiGLSL] version 0.0.12
[Taichi] Starting on arch=x64


![图片](https://github.com/user-attachments/assets/cb6e7e5c-e1a1-4977-b246-a207b4ba4e08)

**Comment by theAfish** [comment]
关于cpu无法渲染图像的问题我这边没有遇到过，猜测有可能是运行效率问题，他可能需要运行一会才能正常显示。

图片保存可以参考Taichi官方文档中导出图像、动图或视频内容：[https://docs.taichi-lang.org/zh-Hans/docs/export_results/](url)，使用ti.GUI.show(文件名)可将渲染图片保存至文件中。由于之前本人的保存脚本已经丢失，且版本存在很大差异，故最好参考官方文档。

**Comment by zhaozhh** [comment]
谢谢您的提示！！！
